deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: yMCR3m2DdcLpVoZTH+/8fOZ/RiZ8zV8+PezH2cnUEJjH8GRrs7h0OjPYGFILgeeN1OoB6CxBaNpOLNfkeHlQ6AVtsNHJ2CdLB9RvL6+DsG6hVqOcL4drTZtQJRk2ZPtWr1hT6BNkrP8/pOu6war+MALJ+01n7Wj/Ot+m8Qp5TXT82man6bkUJMGKbiTHOh6I58R3sSjLcXiTL6kEifUenu5go1w9l5gX3NzaentHsB8mDdWi2EN4rALBkVub+cCLAowERxvG+kYgjPSTe3F2X2RI5DDO9/zCZiOOI7mgJQgx/NNNRdVre2RgjrDy6RxXuYME5pjfVRr8h7boBlwidpiY6oDGeZoDXr9S+41AgV5z3wKmf++Q6EpzgfDBgb1GD4kycXbkp10zhJu2fn8pSjQERG9ve9lqpoUzaS9NG3sX4r1UwiuBz8FPksRGxtD1xG0xjZnUumXfxfl+Ge5mEjRSZbLT76q7cearDnD9Qx2Z9DFrrjvt66jdmaOfxsbdzXMiLCLPy6Ht3luEhYbvhyKf1jlvd78qXypVnp0DPZhVcLaq1HW2wA4ZmS9g7ZnvxtCNfxwwbf1Uy7AGhuRBFS88mr1th7BJvd23aNdjPENOBMxeFInjzQ06E2vXRt3TzJVn1ViBhVGFyU1uh1x7apne7XmOPAPt4XKIFYMx9QA=
  on:
    python: 2.7
    repo: graphql-python/graphql-ws
    tags: true
install: pip install -U tox-travis
language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
script: tox
